# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dda4e9990f9fcde0427e64fb85fde5ebf7f1011221a702ecee14adcbcda516617e8b9a5d8707f6cf913ae00e54e607f7ef8227615e87afee95a71ce96191f603

test:
  secret_key_base: 2763f05d8c05d4f14d6952e677f3377e29906b7802a29b40c3d048d95df4030ea822fd7c53f3194b7dcaecbdbeef8580819600c93f4630ccdeff3f0803bbc36f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
